#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build a frozen, label-separated external structure-analysis fixture.

The six inputs are fixed public mathematical TeX sources cached outside the
repository.  For each source this tool deterministically:

* samples genuine theorem-like environments from the front, middle and back;
* removes only the selected outer ``begin``/``end`` pair and adds a visible
  OCR-style heading (the environment body remains byte-for-byte identical in
  normalized UTF-8 text);
* samples nearby top-level narrative/cross-reference paragraphs as negatives;
* writes a packet file with no answers and a physically separate gold file.

Unit IDs are the full source SHA-256 plus the original 1-based line interval.
No model is called and no prediction is generated by this script.

Default invocation (from the repository root)::

    python tools/build_external_blind_fixture.py

The default corpus and output directories are respectively
``../work/external-corpus`` and ``../work/external-results``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from latexstruct.core.parser import (  # noqa: E402
    Block,
    Document,
    normalize_newlines,
    offset_to_line,
    parse_latex,
)


CANONICAL_TITLES = {
    "theorem": "Theorem",
    "lemma": "Lemma",
    "definition": "Definition",
    "proposition": "Proposition",
    "corollary": "Corollary",
    "remark": "Remark",
    "example": "Example",
    "proof": "Proof",
}
ALLOWED_ENVS = tuple(CANONICAL_TITLES)
REGION_NAMES = ("front", "middle", "back")
XREF_RE = re.compile(
    r"\\(?:[Cc]ref|ref|autoref|eqref|pageref|cite\w*)\b"
    r"|\b(?:Theorem|Lemma|Definition|Proposition|Corollary|Remark|Example|Proof)\b"
)
STRUCTURAL_START_RE = re.compile(
    r"^\\(?:part|chapter|section|subsection|subsubsection|paragraph|"
    r"begin|end|bibliography|printbibliography|maketitle|tableofcontents)\b"
)


@dataclass(frozen=True)
class SourceSpec:
    document_id: str
    label: str
    source_kind: str
    relative_path: str
    env_map: dict[str, str]
    source_url: str
    version: str
    license: str


@dataclass(frozen=True)
class EnvironmentItem:
    raw_env: str
    env: str
    begin_start: int
    begin_end: int
    end_start: int
    end_end: int
    start_line: int
    end_line: int
    region: int

    @property
    def midpoint(self) -> float:
        return (self.start_line + self.end_line) / 2


@dataclass(frozen=True)
class NegativeItem:
    block: Block
    class_name: str
    region: int

    @property
    def midpoint(self) -> float:
        return (self.block.span.start_line + self.block.span.end_line) / 2


SOURCES = (
    SourceSpec(
        "D01",
        "GIAM v3.2 / proof1",
        "book",
        "books/giam/proof1/proof1.tex",
        {"thm": "theorem", "defi": "definition", "proof": "proof"},
        "https://github.com/osj1961/giam",
        "v3.2 / b80803b311bdc5eaedc5ed511ed1945225e804bb",
        "GFDL-1.3",
    ),
    SourceSpec(
        "D02",
        "Homotopy Type Theory / basics",
        "book",
        "books/hott-book/basics.tex",
        {
            "thm": "theorem",
            "lem": "lemma",
            "defn": "definition",
            "cor": "corollary",
            "rmk": "remark",
            "eg": "example",
            "proof": "proof",
        },
        "https://github.com/HoTT/book",
        "578b85cc8d586b1677ec4335148adeb443057d24",
        "CC-BY-SA-3.0",
    ),
    SourceSpec(
        "D03",
        "The Stacks Project / fields",
        "book",
        "books/stacks-project/fields.tex",
        {
            "theorem": "theorem",
            "lemma": "lemma",
            "definition": "definition",
            "example": "example",
            "proof": "proof",
        },
        "https://github.com/stacks/stacks-project",
        "a04446e57ec1fbc252a871afcec7752fb2807b14",
        "GFDL-1.2-or-later",
    ),
    SourceSpec(
        "D04",
        "Real and finite field versions of Chebotarev's theorem",
        "paper",
        "extracted/papers/emmrich-2506.02947v2/main.tex",
        {
            "theorem": "theorem",
            "lemma": "lemma",
            "definition": "definition",
            "proposition": "proposition",
            "corollary": "corollary",
            "Corollary": "corollary",
            "remark": "remark",
            "example": "example",
            "proof": "proof",
        },
        "https://arxiv.org/abs/2506.02947v2",
        "2506.02947v2",
        "CC-BY-4.0",
    ),
    SourceSpec(
        "D05",
        "Almost arithmetic progressions in the primes and other large sets",
        "paper",
        "extracted/papers/fraser-1809.01409v2/almostAPs.tex",
        {"thm": "theorem", "lma": "lemma", "defn": "definition"},
        "https://arxiv.org/abs/1809.01409v2",
        "1809.01409v2",
        "arXiv perpetual non-exclusive license",
    ),
    SourceSpec(
        "D06",
        "Perfectoid Spaces",
        "paper",
        "extracted/papers/scholze-1111.4914v1/PhDThesis.tex",
        {
            "thm": "theorem",
            "lem": "lemma",
            "definition": "definition",
            "prop": "proposition",
            "cor": "corollary",
            "rem": "remark",
            "example": "example",
            "proof": "proof",
        },
        "https://arxiv.org/abs/1111.4914v1",
        "1111.4914v1",
        "arXiv perpetual non-exclusive license",
    ),
)


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _sha256_text(text: str) -> str:
    return _sha256_bytes(text.encode("utf-8"))


def _read_source(path: Path) -> tuple[bytes, str, str]:
    raw = path.read_bytes()
    if raw.startswith(b"\xef\xbb\xbf"):
        decoded = raw.decode("utf-8-sig")
        encoding = "utf-8-sig"
    else:
        try:
            decoded = raw.decode("utf-8")
            encoding = "utf-8"
        except UnicodeDecodeError:
            decoded = raw.decode("latin-1")
            encoding = "latin-1-fallback"
    return raw, normalize_newlines(decoded), encoding


def _region(line: float, total_lines: int) -> int:
    return min(2, max(0, int((max(1.0, line) - 1) * 3 / max(1, total_lines))))


def _unit_id(source_sha256: str, start_line: int, end_line: int) -> str:
    return f"sha256:{source_sha256}:{start_line:06d}-{end_line:06d}"


def _evenly_spaced(items: Sequence, count: int) -> list:
    """Return up to ``count`` deterministic, position-spread unique items."""
    if count <= 0:
        return []
    if len(items) <= count:
        return list(items)
    if count == 1:
        return [items[len(items) // 2]]
    indices = [round(i * (len(items) - 1) / (count - 1)) for i in range(count)]
    # round() can only collide for pathological small inputs, but preserve the
    # requested count defensively by filling from left to right.
    chosen_indices: list[int] = []
    for index in indices:
        if index not in chosen_indices:
            chosen_indices.append(index)
    for index in range(len(items)):
        if len(chosen_indices) >= count:
            break
        if index not in chosen_indices:
            chosen_indices.append(index)
    return [items[index] for index in sorted(chosen_indices)]


def _select_by_thirds(items: Sequence, target: int) -> list:
    """Select by thirds, then swap duplicates to retain environment diversity."""
    ordered = sorted(items, key=lambda item: (item.midpoint, repr(item)))
    per_region_goal = target // 3
    selected: list = []
    for region_index in range(3):
        group = [item for item in ordered if item.region == region_index]
        selected.extend(_evenly_spaced(group, min(per_region_goal, len(group))))
    selected_ids = {id(item) for item in selected}
    remaining = [item for item in ordered if id(item) not in selected_ids]
    selected.extend(_evenly_spaced(remaining, min(target - len(selected), len(remaining))))

    # Position-only sampling can accidentally omit a rare definition,
    # proposition, or corollary. Preserve the regional quotas while replacing
    # redundant selected environments with every real canonical environment
    # available in this document (there are at most eight supported kinds).
    available_envs = sorted({item.env for item in ordered})
    for missing_env in available_envs:
        if any(item.env == missing_env for item in selected):
            continue
        candidates = [item for item in ordered if item.env == missing_env]
        replacement = candidates[len(candidates) // 2]
        env_counts = Counter(item.env for item in selected)
        victims = [
            item
            for item in selected
            if item.region == replacement.region and env_counts[item.env] > 1
        ]
        if not victims:
            continue
        victim = min(
            victims,
            key=lambda item: (
                -env_counts[item.env],
                abs(item.midpoint - replacement.midpoint),
                item.midpoint,
            ),
        )
        selected[selected.index(victim)] = replacement
    return sorted(selected, key=lambda item: item.midpoint)


def _atomic_body_fragments(body: str, maximum: int = 12) -> list[str]:
    """Split at blank lines without adding, deleting, or reordering a character."""
    if not body:
        return []
    pieces: list[str] = []
    start = 0
    for match in re.finditer(r"\n[ \t]*\n", body):
        pieces.append(body[start : match.end()])
        start = match.end()
    pieces.append(body[start:])
    pieces = [piece for piece in pieces if piece]

    # Whitespace-only pieces are not meaningful atomic units.  Merge them into
    # the next piece where possible (or the previous final piece) losslessly.
    merged: list[str] = []
    prefix = ""
    for piece in pieces:
        if not piece.strip():
            prefix += piece
            continue
        merged.append(prefix + piece)
        prefix = ""
    if prefix:
        if merged:
            merged[-1] += prefix
        else:
            merged.append(prefix)

    if len(merged) <= maximum:
        return merged
    grouped: list[str] = []
    for index in range(maximum):
        left = index * len(merged) // maximum
        right = (index + 1) * len(merged) // maximum
        grouped.append("".join(merged[left:right]))
    return grouped


def _environment_items(
    spec: SourceSpec,
    doc: Document,
    total_lines: int,
    text: str,
    max_chars: int,
) -> tuple[list[EnvironmentItem], list[dict]]:
    items: list[EnvironmentItem] = []
    skips: list[dict] = []
    raw_targets: list[EnvironmentItem] = []
    preamble_end = doc.preamble_span.end_line if doc.preamble_span else 0
    for raw_env, begin_start, begin_end, end_start, end_end in doc.env_ranges:
        if raw_env not in spec.env_map:
            continue
        start_line = offset_to_line(doc.line_starts, begin_start)
        end_line = offset_to_line(doc.line_starts, max(begin_start, end_end - 1))
        raw_targets.append(
            EnvironmentItem(
                raw_env,
                spec.env_map[raw_env],
                begin_start,
                begin_end,
                end_start,
                end_end,
                start_line,
                end_line,
                _region((start_line + end_line) / 2, total_lines),
            )
        )

    for item in raw_targets:
        reason = ""
        if item.start_line <= preamble_end:
            reason = "preamble-or-environment-declaration-example"
        else:
            for other in raw_targets:
                if other is item:
                    continue
                overlaps_by_nesting = (
                    item.begin_start < other.begin_start < other.end_end <= item.end_end
                    or other.begin_start < item.begin_start < item.end_end <= other.end_end
                )
                if overlaps_by_nesting:
                    reason = "nested-theorem-like-environment"
                    break
        body = text[item.begin_end : item.end_start]
        if not reason and not body.strip():
            reason = "empty-body"
        if not reason and len(body) > max_chars:
            reason = "body-exceeds-packet-limit"
        begin_or_end_inside = re.search(
            rf"\\(?:begin|end)\s*\{{{re.escape(item.raw_env)}\}}", body
        )
        if not reason and begin_or_end_inside:
            reason = "same-environment-marker-inside-body"
        if reason:
            skips.append(
                {
                    "raw_env": item.raw_env,
                    "canonical_env": item.env,
                    "start_line": item.start_line,
                    "end_line": item.end_line,
                    "reason": reason,
                }
            )
        else:
            items.append(item)
    return items, skips


def _normal_paragraphs(doc: Document, total_lines: int, max_chars: int) -> list[NegativeItem]:
    result: list[NegativeItem] = []
    preamble_end = doc.preamble_span.end_line if doc.preamble_span else 0
    for block in doc.blocks_of_kind("para"):
        stripped = block.text.strip()
        if block.in_env or block.span.start_line <= preamble_end:
            continue
        if len(stripped) < 50 or len(block.text) > max_chars:
            continue
        if "\\begin{" in block.text or "\\end{" in block.text:
            continue
        if STRUCTURAL_START_RE.match(stripped):
            continue
        if stripped.startswith(("%", "\\[", "$$", "\\item", "\\label")):
            continue
        class_name = "cross-reference" if XREF_RE.search(block.text) else "narrative"
        result.append(
            NegativeItem(
                block,
                class_name,
                _region((block.span.start_line + block.span.end_line) / 2, total_lines),
            )
        )
    return result


def _distance_to_positives(item: NegativeItem, positives: Sequence[EnvironmentItem]) -> float:
    if not positives:
        return item.midpoint
    return min(abs(item.midpoint - positive.midpoint) for positive in positives)


def _select_negatives(
    items: Sequence[NegativeItem],
    positives: Sequence[EnvironmentItem],
    target: int,
) -> list[NegativeItem]:
    """Choose nearby xref/narrative negatives with balanced document thirds."""
    selected: list[NegativeItem] = []
    per_region_goal = target // 3
    for region_index in range(3):
        group = [item for item in items if item.region == region_index]
        ranked = sorted(
            group,
            key=lambda item: (
                _distance_to_positives(item, positives),
                item.block.span.start_line,
            ),
        )
        xrefs = [item for item in ranked if item.class_name == "cross-reference"]
        narratives = [item for item in ranked if item.class_name == "narrative"]
        half = per_region_goal // 2
        region_selected = xrefs[:half] + narratives[:half]
        used = {item.block.id for item in region_selected}
        region_selected.extend(
            item
            for item in ranked
            if item.block.id not in used
            and len(region_selected) < per_region_goal
        )
        selected.extend(region_selected)

    used = {item.block.id for item in selected}
    remaining = sorted(
        (item for item in items if item.block.id not in used),
        key=lambda item: (
            _distance_to_positives(item, positives),
            item.block.span.start_line,
        ),
    )
    selected.extend(remaining[: max(0, target - len(selected))])
    return sorted(selected[:target], key=lambda item: item.midpoint)


def _nearest_context(
    normal_items: Sequence[NegativeItem],
    start_line: int,
    end_line: int,
    excluded_block_id: int | None = None,
) -> tuple[Block | None, Block | None]:
    usable = [
        item.block
        for item in normal_items
        if excluded_block_id is None or item.block.id != excluded_block_id
    ]
    before = [block for block in usable if block.span.end_line < start_line]
    after = [block for block in usable if block.span.start_line > end_line]
    return (
        max(before, key=lambda block: block.span.end_line) if before else None,
        min(after, key=lambda block: block.span.start_line) if after else None,
    )


def _append_packet_block(blocks: list[dict], text: str) -> int:
    # The production accuracy scorer deliberately accepts only non-negative
    # integer atomic block identifiers, which prevents loose string coercion.
    block_id = len(blocks)
    blocks.append({"id": block_id, "text": text})
    return block_id


def _positive_unit(
    spec: SourceSpec,
    source_sha256: str,
    text: str,
    item: EnvironmentItem,
    normal_items: Sequence[NegativeItem],
) -> tuple[dict, dict]:
    body = text[item.begin_end : item.end_start]
    body_fragments = _atomic_body_fragments(body)
    if not body_fragments:
        raise ValueError(f"empty selected environment body at {item.start_line}")
    before, after = _nearest_context(normal_items, item.start_line, item.end_line)
    blocks: list[dict] = []
    if before:
        _append_packet_block(blocks, before.text)
    title_block = _append_packet_block(blocks, f"{CANONICAL_TITLES[item.env]}.")
    body_block_ids = [
        _append_packet_block(blocks, fragment) for fragment in body_fragments
    ]
    if after:
        _append_packet_block(blocks, after.text)
    unit_id = _unit_id(source_sha256, item.start_line, item.end_line)
    packet = {
        "id": unit_id,
        "document_id": spec.document_id,
        "document_region": REGION_NAMES[item.region],
        "focus_anchor": title_block,
        "blocks": blocks,
    }
    gold = {
        "id": unit_id,
        "document": spec.document_id,
        "sample_kind": "ocr-bare-heading",
        "source_start_line": item.start_line,
        "source_end_line": item.end_line,
        "source_raw_env": item.raw_env,
        "action": "wrap",
        "env": item.env,
        "start_block": title_block,
        "end_block": body_block_ids[-1],
        "body_block_ids": body_block_ids,
        "source_body_sha256": _sha256_text(body),
        "source_body_chars": len(body),
        "packet_blocks_sha256": _sha256_text(
            json.dumps(blocks, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        ),
    }
    return packet, gold


def _negative_unit(
    spec: SourceSpec,
    source_sha256: str,
    item: NegativeItem,
    normal_items: Sequence[NegativeItem],
) -> tuple[dict, dict]:
    block = item.block
    before, after = _nearest_context(
        normal_items,
        block.span.start_line,
        block.span.end_line,
        excluded_block_id=block.id,
    )
    blocks: list[dict] = []
    if before:
        _append_packet_block(blocks, before.text)
    focus_block = _append_packet_block(blocks, block.text)
    if after:
        _append_packet_block(blocks, after.text)
    unit_id = _unit_id(source_sha256, block.span.start_line, block.span.end_line)
    packet = {
        "id": unit_id,
        "document_id": spec.document_id,
        "document_region": REGION_NAMES[item.region],
        "focus_anchor": focus_block,
        "blocks": blocks,
    }
    gold = {
        "id": unit_id,
        "document": spec.document_id,
        "sample_kind": item.class_name,
        "source_start_line": block.span.start_line,
        "source_end_line": block.span.end_line,
        "action": "preserve",
        "env": "",
        "start_block": focus_block,
        "end_block": focus_block,
        "source_text_sha256": _sha256_text(block.text),
        "source_text_chars": len(block.text),
        "packet_blocks_sha256": _sha256_text(
            json.dumps(blocks, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
        ),
    }
    return packet, gold


def _validate_fixture(
    packets: dict,
    gold: dict,
    negative_target: int,
    corpus_root: Path,
) -> dict:
    errors: list[str] = []
    packet_units = packets.get("units", [])
    gold_units = gold.get("units", [])
    packet_ids = [unit.get("id") for unit in packet_units]
    gold_ids = [unit.get("id") for unit in gold_units]
    if len(packet_ids) != len(set(packet_ids)):
        errors.append("packet unit IDs are not unique")
    if len(gold_ids) != len(set(gold_ids)):
        errors.append("gold unit IDs are not unique")
    if set(packet_ids) != set(gold_ids):
        errors.append("packet/gold unit ID sets differ")
    packet_by_id = {unit["id"]: unit for unit in packet_units}
    source_snapshots: dict[str, dict] = {}
    for document in gold.get("documents", []):
        source_path = corpus_root / document["source_path"]
        raw, source_text, _encoding = _read_source(source_path)
        source_sha256 = _sha256_bytes(raw)
        if source_sha256 != document.get("source_sha256"):
            errors.append(f"{document['document_id']}: reopened source hash mismatch")
        source_doc = parse_latex(source_text)
        env_bodies: dict[tuple[str, int, int], str] = {}
        for raw_env, _bs, begin_end, end_start, end_end in source_doc.env_ranges:
            start_line = offset_to_line(source_doc.line_starts, _bs)
            end_line = offset_to_line(source_doc.line_starts, max(_bs, end_end - 1))
            env_bodies[(raw_env, start_line, end_line)] = source_text[begin_end:end_start]
        paragraph_text = {
            (block.span.start_line, block.span.end_line): block.text
            for block in source_doc.blocks_of_kind("para")
        }
        source_snapshots[document["document_id"]] = {
            "sha256": source_sha256,
            "environment_bodies": env_bodies,
            "paragraph_text": paragraph_text,
        }
    per_document: dict[str, Counter] = {}
    for answer in gold_units:
        unit_id = answer["id"]
        packet = packet_by_id.get(unit_id)
        if not packet:
            continue
        blocks = packet.get("blocks", [])
        block_ids = [block.get("id") for block in blocks]
        if len(block_ids) != len(set(block_ids)) or not block_ids:
            errors.append(f"{unit_id}: invalid packet blocks")
            continue
        start_block = answer.get("start_block")
        end_block = answer.get("end_block")
        if start_block not in block_ids or end_block not in block_ids:
            errors.append(f"{unit_id}: gold boundary does not exist in packet")
            continue
        if block_ids.index(start_block) > block_ids.index(end_block):
            errors.append(f"{unit_id}: reversed gold boundary")
        if packet.get("focus_anchor") != start_block:
            errors.append(f"{unit_id}: focus anchor/gold start disagree")
        canonical_blocks = json.dumps(
            blocks, ensure_ascii=False, sort_keys=True, separators=(",", ":")
        )
        if _sha256_text(canonical_blocks) != answer.get("packet_blocks_sha256"):
            errors.append(f"{unit_id}: packet blocks hash mismatch")
        by_id = {block["id"]: block["text"] for block in blocks}
        snapshot = source_snapshots.get(answer["document"], {})
        expected_id = _unit_id(
            snapshot.get("sha256", ""),
            answer["source_start_line"],
            answer["source_end_line"],
        )
        if expected_id != unit_id:
            errors.append(f"{unit_id}: ID does not match reopened source hash/line interval")
        if answer.get("action") == "wrap":
            if answer.get("env") not in ALLOWED_ENVS:
                errors.append(f"{unit_id}: unsupported gold environment")
            body = "".join(by_id[block_id] for block_id in answer["body_block_ids"])
            if _sha256_text(body) != answer.get("source_body_sha256"):
                errors.append(f"{unit_id}: theorem body was not conserved")
            source_body = snapshot.get("environment_bodies", {}).get(
                (
                    answer["source_raw_env"],
                    answer["source_start_line"],
                    answer["source_end_line"],
                )
            )
            if source_body is None:
                errors.append(f"{unit_id}: source environment cannot be reopened exactly")
            elif body != source_body:
                errors.append(f"{unit_id}: packet body differs from reopened source body")
            raw_env = re.escape(answer["source_raw_env"])
            if re.search(rf"\\(?:begin|end)\s*\{{{raw_env}\}}", body):
                errors.append(f"{unit_id}: selected outer environment marker remains")
        elif answer.get("action") == "preserve":
            if start_block != end_block or answer.get("env"):
                errors.append(f"{unit_id}: invalid preservation gold")
            if _sha256_text(by_id[start_block]) != answer.get("source_text_sha256"):
                errors.append(f"{unit_id}: negative source paragraph was not conserved")
            source_paragraph = snapshot.get("paragraph_text", {}).get(
                (answer["source_start_line"], answer["source_end_line"])
            )
            if source_paragraph is None:
                errors.append(f"{unit_id}: negative source paragraph cannot be reopened exactly")
            elif by_id[start_block] != source_paragraph:
                errors.append(f"{unit_id}: negative differs from reopened source paragraph")
        else:
            errors.append(f"{unit_id}: invalid gold action")
        counts = per_document.setdefault(answer["document"], Counter())
        counts[answer["action"]] += 1
        counts[f"region:{packet['document_region']}"] += 1

    for document in gold.get("documents", []):
        counts = per_document.get(document["document_id"], Counter())
        if counts["preserve"] < negative_target:
            errors.append(
                f"{document['document_id']}: fewer than {negative_target} real negatives"
            )
        for region_name in REGION_NAMES:
            if counts[f"region:{region_name}"] == 0:
                errors.append(f"{document['document_id']}: no units in {region_name}")

    banned_packet_keys = {
        "action",
        "env",
        "start_block",
        "end_block",
        "sample_kind",
        "source_path",
        "body_block_ids",
    }

    def walk(value) -> Iterable[str]:
        if isinstance(value, dict):
            for key, child in value.items():
                yield key
                yield from walk(child)
        elif isinstance(value, list):
            for child in value:
                yield from walk(child)

    leaked = sorted(set(walk(packets)) & banned_packet_keys)
    if leaked:
        errors.append(f"answer-bearing keys leaked into packet: {leaked}")
    return {
        "schema": "latexstruct-external-blind-validation-v1",
        "passed": not errors,
        "unit_count": len(packet_units),
        "packet_gold_id_sets_equal": set(packet_ids) == set(gold_ids),
        "body_and_negative_text_conservation_checked": len(gold_units),
        "sources_reopened_for_independent_check": len(source_snapshots),
        "answer_keys_absent_from_packets": not leaked,
        "errors": errors,
    }


def build_fixture(
    corpus_root: Path,
    positive_target: int,
    negative_target: int,
    max_positive_chars: int,
    max_negative_chars: int,
) -> tuple[dict, dict, dict]:
    packet_units: list[dict] = []
    gold_units: list[dict] = []
    documents: list[dict] = []
    packet_documents: list[dict] = []

    for spec in SOURCES:
        source_path = corpus_root / Path(spec.relative_path)
        if not source_path.is_file():
            raise FileNotFoundError(source_path)
        raw, text, encoding = _read_source(source_path)
        source_sha256 = _sha256_bytes(raw)
        total_lines = len(text.splitlines())
        doc = parse_latex(text)
        safe_environments, unsafe_skips = _environment_items(
            spec, doc, total_lines, text, max_positive_chars
        )
        selected_environments = _select_by_thirds(safe_environments, positive_target)
        normal_items = _normal_paragraphs(doc, total_lines, max_negative_chars)
        selected_negatives = _select_negatives(
            normal_items, selected_environments, negative_target
        )

        source_packets: list[dict] = []
        source_gold: list[dict] = []
        for item in selected_environments:
            packet, answer = _positive_unit(
                spec, source_sha256, text, item, normal_items
            )
            source_packets.append(packet)
            source_gold.append(answer)
        for item in selected_negatives:
            packet, answer = _negative_unit(
                spec, source_sha256, item, normal_items
            )
            source_packets.append(packet)
            source_gold.append(answer)
        order = {
            unit["id"]: (unit["source_start_line"], unit["sample_kind"])
            for unit in source_gold
        }
        source_packets.sort(key=lambda unit: order[unit["id"]])
        source_gold.sort(key=lambda unit: (unit["source_start_line"], unit["sample_kind"]))
        packet_units.extend(source_packets)
        gold_units.extend(source_gold)

        positive_regions = Counter(REGION_NAMES[item.region] for item in selected_environments)
        negative_regions = Counter(REGION_NAMES[item.region] for item in selected_negatives)
        negative_classes = Counter(item.class_name for item in selected_negatives)
        shortfall = max(0, positive_target - len(selected_environments))
        documents.append(
            {
                "document_id": spec.document_id,
                "label": spec.label,
                "source_kind": spec.source_kind,
                "source_path": spec.relative_path,
                "source_url": spec.source_url,
                "version": spec.version,
                "license": spec.license,
                "encoding": encoding,
                "source_bytes": len(raw),
                "source_lines": total_lines,
                "source_sha256": source_sha256,
                "mapped_environments": spec.env_map,
                "safe_real_environment_count": len(safe_environments),
                "sampled_positive_count": len(selected_environments),
                "positive_target": positive_target,
                "positive_shortfall": shortfall,
                "positive_goal_met": shortfall == 0,
                "positive_by_region": {
                    region: positive_regions[region] for region in REGION_NAMES
                },
                "sampled_negative_count": len(selected_negatives),
                "negative_target": negative_target,
                "negative_by_region": {
                    region: negative_regions[region] for region in REGION_NAMES
                },
                "negative_by_class": dict(sorted(negative_classes.items())),
                "unsafe_skip_count": len(unsafe_skips),
                "unsafe_skip_by_reason": dict(
                    sorted(Counter(item["reason"] for item in unsafe_skips).items())
                ),
                "unsafe_skips": unsafe_skips,
                "parser_unbalanced_begins": list(doc.unbalanced_begins),
                "parser_unbalanced_ends": list(doc.unbalanced_ends),
                "sampling_note": (
                    "All available safe real target environments were used; no duplicates "
                    "or synthetic copies were added."
                    if shortfall
                    else "Target met with unique real source environments."
                ),
            }
        )
        packet_documents.append(
            {
                "document_id": spec.document_id,
                "source_kind": spec.source_kind,
                "source_sha256": source_sha256,
                "unit_count": len(source_packets),
            }
        )

    packet_units.sort(key=lambda unit: (unit["document_id"], unit["id"]))
    gold_units.sort(
        key=lambda unit: (unit["document"], unit["source_start_line"], unit["sample_kind"])
    )
    packets = {
        "schema": "latexstruct-external-blind-packets-v1",
        "instructions": {
            "task": (
                "For each unit, decide whether the focus anchor and following atomic blocks "
                "form one bare mathematical structure or should remain unchanged."
            ),
            "response": (
                "Return exactly one object per unit with id, action, env, start_block, "
                "and end_block."
            ),
            "allowed_actions": ["wrap", "preserve", "manual"],
            "allowed_environments": list(ALLOWED_ENVS),
            "boundary_rule": (
                "For wrap, include the complete structure but exclude surrounding narrative. "
                "For preserve/manual, use the focus anchor for both boundaries."
            ),
            "blindness_rule": (
                "Use only this packet. Do not open the source paths or the separate gold file."
            ),
        },
        "documents": packet_documents,
        "units": packet_units,
    }
    gold = {
        "schema": "latexstruct-external-blind-gold-v1",
        "sampling": {
            "positive_target_per_document": positive_target,
            "negative_target_per_document": negative_target,
            "regions": list(REGION_NAMES),
            "positive_method": (
                "Unique real mapped theorem-like environments, four spread samples per absolute "
                "document third where available; outer begin/end removed, canonical OCR heading "
                "added, inner body conserved exactly."
            ),
            "negative_method": (
                "Top-level real narrative/cross-reference paragraphs nearest sampled positives, "
                "balanced across absolute document thirds."
            ),
            "known_shortfall_policy": (
                "Never duplicate or fabricate a real source environment merely to hit a quota."
            ),
        },
        "documents": documents,
        "units": gold_units,
    }
    validation = _validate_fixture(packets, gold, negative_target, corpus_root)
    validation["documents"] = [
        {
            "document_id": document["document_id"],
            "positive": document["sampled_positive_count"],
            "negative": document["sampled_negative_count"],
            "positive_goal_met": document["positive_goal_met"],
            "positive_by_region": document["positive_by_region"],
            "negative_by_region": document["negative_by_region"],
        }
        for document in documents
    ]
    validation["summary"] = {
        "document_count": len(documents),
        "positive_count": sum(document["sampled_positive_count"] for document in documents),
        "negative_count": sum(document["sampled_negative_count"] for document in documents),
        "positive_by_environment": dict(
            sorted(
                Counter(
                    unit["env"] for unit in gold_units if unit["action"] == "wrap"
                ).items()
            )
        ),
        "negative_by_class": dict(
            sorted(
                Counter(
                    unit["sample_kind"]
                    for unit in gold_units
                    if unit["action"] == "preserve"
                ).items()
            )
        ),
        "positive_goal_documents": sum(document["positive_goal_met"] for document in documents),
        "positive_shortfall_documents": sum(
            not document["positive_goal_met"] for document in documents
        ),
        "unsafe_skip_count": sum(document["unsafe_skip_count"] for document in documents),
    }
    return packets, gold, validation


def _write_json(path: Path, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--corpus-root",
        type=Path,
        default=REPO_ROOT.parent / "work" / "external-corpus",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=REPO_ROOT.parent / "work" / "external-results",
    )
    parser.add_argument("--positive-per-document", type=int, default=12)
    parser.add_argument("--negative-per-document", type=int, default=12)
    parser.add_argument("--max-positive-chars", type=int, default=8000)
    parser.add_argument("--max-negative-chars", type=int, default=2500)
    args = parser.parse_args()
    if args.positive_per_document < 1 or args.negative_per_document < 1:
        parser.error("sample targets must be positive")
    try:
        packets, gold, validation = build_fixture(
            args.corpus_root.resolve(),
            args.positive_per_document,
            args.negative_per_document,
            args.max_positive_chars,
            args.max_negative_chars,
        )
    except (OSError, UnicodeError, ValueError) as exc:
        parser.error(str(exc))

    output_dir = args.output_dir.resolve()
    _write_json(output_dir / "blind-packets.json", packets)
    _write_json(output_dir / "blind-gold.json", gold)
    _write_json(output_dir / "blind-validation.json", validation)
    print(json.dumps(validation, ensure_ascii=False, indent=2))
    return 0 if validation["passed"] else 1


if __name__ == "__main__":
    raise SystemExit(main())
